# Category Keywords Configuration for Metabolical Backend
# This file defines the mapping between categories and their associated keywords/tags
# The structure follows: categories -> category_name -> title & tags

categories:
  news:
    title: "News"
    tags:
      - "latest"
      - "policy and regulation"
      - "govt schemes"
      - "international"
      - "recent"
      - "new"
      - "current"
      - "today"
      - "breaking news"
      - "health policy"
      - "medical regulation"
      - "government schemes"
      - "public health programs"
      - "global health"
      - "world health"
      - "who"
      - "research study"
      - "clinical trial"
      - "medical research"

  diseases:
    title: "Diseases"
    tags:
      - "diabetes"
      - "obesity"
      - "inflammation"
      - "cardiovascular"
      - "liver"
      - "kidney"
      - "thyroid"
      - "metabolic"
      - "sleep disorders"
      - "skin"
      - "eyes and ears"
      - "reproductive health"
      - "blood sugar"
      - "insulin"
      - "glucose"
      - "heart disease"
      - "cardiac"
      - "heart attack"
      - "stroke"
      - "hypertension"
      - "high blood pressure"
      - "cancer"
      - "tumor"
      - "chronic inflammation"
      - "inflammatory"
      - "overweight"
      - "weight gain"
      - "bmi"
      - "liver disease"
      - "fatty liver"
      - "kidney disease"
      - "thyroid disorder"
      - "metabolic syndrome"
      - "insomnia"
      - "sleep apnea"
      - "acne"
      - "eczema"
      - "psoriasis"
      - "vision problems"
      - "hearing loss"
      - "fertility"
      - "infertility"

  solutions:
    title: "Solutions"
    tags:
      - "nutrition"
      - "fitness"
      - "lifestyle"
      - "wellness"
      - "prevention"
      - "exercise"
      - "workout"
      - "physical activity"
      - "diet"
      - "healthy eating"
      - "vitamins"
      - "minerals"
      - "treatment"
      - "therapy"
      - "medication"
      - "surgery"
      - "preventive care"
      - "screening"
      - "vaccination"
      - "holistic health"
      - "self-care"
      - "meditation"
      - "mindfulness"
      - "stress management"
      - "behavior modification"

  food:
    title: "Food"
    tags:
      - "natural food"
      - "organic food"
      - "processed food"
      - "fish and seafood"
      - "food safety"
      - "organic"
      - "whole foods"
      - "unprocessed"
      - "superfood"
      - "pesticide free"
      - "chemical free"
      - "sustainable food"
      - "packaged food"
      - "fast food"
      - "junk food"
      - "salmon"
      - "tuna"
      - "omega-3"
      - "food poisoning"
      - "contamination"
      - "food recall"
      - "nutrition"
      - "dietary"
      - "antioxidants"

  audience:
    title: "Audience"
    tags:
      - "women"
      - "men"
      - "children"
      - "teenagers"
      - "seniors"
      - "athletes"
      - "families"
      - "women's health"
      - "female health"
      - "pregnancy"
      - "menstruation"
      - "menopause"
      - "men's health"
      - "male health"
      - "prostate"
      - "testosterone"
      - "children's health"
      - "pediatric"
      - "kids health"
      - "teen health"
      - "adolescent health"
      - "elderly health"
      - "senior health"
      - "aging"
      - "geriatric"
      - "sports medicine"
      - "athlete health"
      - "family health"
      - "household health"

  trending:
    title: "Trending"
    tags:
      - "gut health"
      - "mental health"
      - "hormones"
      - "addiction"
      - "sleep health"
      - "sexual wellness"
      - "microbiome"
      - "digestive health"
      - "probiotics"
      - "gut bacteria"
      - "psychological health"
      - "depression"
      - "anxiety"
      - "stress"
      - "hormonal health"
      - "hormone balance"
      - "estrogen"
      - "substance abuse"
      - "dependency"
      - "sleep wellness"
      - "sleep quality"
      - "sexual health"
      - "intimate health"
      - "reproductive wellness"

  blogs_and_opinions:
    title: "Blogs & Opinions"
    tags:
      - "health blog"
      - "wellness blog"
      - "expert opinion"
      - "doctor says"
      - "medical expert"
      - "health tips"
      - "wellness tips"
      - "personal health story"
      - "patient story"
      - "review"
      - "recommendation"
      - "health advice"